#!/bin/bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure the redirection
sudo sed -i '/listen 80 default_server/a location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}' /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration
sudo service nginx restart

