#!/usr/bin/env bash
# install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chown -R "$USER:$USER" /var/www/html
echo "Holberton School" >> /var/www/html/index.html
new_string="_;\n\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/_;/$new_string/" /etc/nginx/sites-available/default
sudo service nginx start
