#!/usr/bin/env bash
# Double the number of webservers.
sudo apt-get update
sudo apt-get -y install nginx
sudo chown $USER:$USER /var/www/html/index.html
sudo touch index.html /var/www/html/
echo 'Hello World!' > /var/www/html/index.html
sudo chown  $USER:$USER /var/www/html/
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo chown  $USER:$USER /etc/nginx/sites-available/
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://github.com/ziomCodes permanent; }' /etc/nginx/sites-available/default
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/html/; internal; }' /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
sudo service nginx restart
